[package]
name = "relex"
version = "0.1.0"
authors = ["Michael Layzell <michael@thelayzells.com>"]
description = "Interpret rust tokens provided by `proc-macro` or `proc-macro2`"
repository = "https://github.com/mystor/relex"
